### ISSUE TITLE
Update APEX to a more recent version in CI, APEX 2.4.1 is deprecated

### ISSUE THREAD

**Issue by aurianer** [pika-org/pika#942] opened 2024-01-10 08:56 UTC
EDIT: only in CSCS CI

**Comment by msimberg** [comment] 2024-01-10 09:42
I'd be fine with doing this only in the new CSCS-CI setup, and letting the old Jenkins setup be with 2.4.1 until it's removed.

**Comment by msimberg** [comment] 2024-02-16 15:32
Duplicate of #948.

**Closed by msimberg** 2024-02-16 15:32 UTC
Labels: priority: medium, type: feature, type: refactoring, category: CI, type: cleanup
